import { Award, BookOpenText, FileCheck2, PenLine } from 'lucide-react';
import { useApp } from '../context/AppContext';
import { t } from '../lib/i18n';
import { SectionHeading } from './SectionHeading';

export function CertificationsBlog() {
  const { copy, locale } = useApp();
  return <section id="certifications" className="section-space"><div className="container-shell grid gap-12 lg:grid-cols-2">
    <div><SectionHeading label={copy.certifications.label} title={copy.certifications.title} subtitle={copy.certifications.subtitle}/><div className="glass-card flex items-start gap-4 p-6"><span className="grid size-12 shrink-0 place-items-center rounded-2xl bg-blue-600 text-white"><Award/></span><div><h3 className="font-black text-slate-950 dark:text-white">{t(locale,'Verified credentials only','یوازې تایید شوي اسناد','فقط مدارک تأییدشده')}</h3><p className="mt-2 leading-7 text-slate-600 dark:text-slate-300">{t(locale,'This section is structured for confirmed certifications, professional development, workshops, and academic credentials. Unverified claims are not displayed.','دا برخه د تایید شوو سرتیفیکېټونو، مسلکي پرمختګ، ورکشاپونو او اکاډمیکو اسنادو لپاره جوړه شوې. ناتایید شوې ادعاوې نه ښودل کېږي.','این بخش برای گواهینامه‌های تأییدشده، رشد حرفه‌ای، کارگاه‌ها و مدارک اکادمیک طراحی شده است. ادعاهای تأییدنشده نمایش داده نمی‌شوند.')}</p></div></div></div>
    <div id="blog"><SectionHeading label={copy.blog.label} title={copy.blog.title} subtitle={copy.blog.subtitle}/><div className="grid gap-4 sm:grid-cols-2"><article className="glass-card p-6"><BookOpenText className="text-violet-600"/><h3 className="mt-5 font-black">{t(locale,'Research notes','څېړنیز یادښتونه','یادداشت‌های پژوهشی')}</h3><p className="mt-2 text-sm leading-6 text-slate-500 dark:text-slate-400">AI, NLP, datasets, evaluation, and low-resource language technology.</p></article><article className="glass-card p-6"><PenLine className="text-cyan-600"/><h3 className="mt-5 font-black">{t(locale,'Tutorials and teaching resources','لارښودونه او تدریسي سرچینې','آموزش‌ها و منابع تدریسی')}</h3><p className="mt-2 text-sm leading-6 text-slate-500 dark:text-slate-400">Python, React, Django, databases, data analytics, ML, and AI.</p></article></div><div className="mt-4 flex items-center gap-3 rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-bold text-emerald-800 dark:border-emerald-400/20 dark:bg-emerald-400/10 dark:text-emerald-200"><FileCheck2 size={18}/>{t(locale,'Blog architecture is ready for future publishing.','د راتلونکي خپرونې لپاره بلاګ جوړښت چمتو دی.','معماری وبلاگ برای نشر آینده آماده است.')}</div></div>
  </div></section>;
}
