import { useMemo, useState } from 'react';
import { motion } from 'motion/react';
import { ExternalLink, Github, Search } from 'lucide-react';
import { useApp } from '../context/AppContext';
import { projects } from '../data/content';
import { t } from '../lib/i18n';
import { SectionHeading } from './SectionHeading';
import { SmartImage } from './SmartImage';
export function Projects() {
  const { copy, locale } = useApp();
  const [category,setCategory]=useState('all'); const [query,setQuery]=useState('');
  const categories=['all','ai','ml','nlp','data','research','web'] as const;
  const labels={all:copy.actions.all,ai:'AI',ml:t(locale,'Machine Learning','ماشین زده‌کړه','یادگیری ماشین'),nlp:'NLP',data:t(locale,'Data Science','ډېټا ساینس','علم داده'),research:copy.nav.research,web:t(locale,'Web Development','وېب پراختیا','توسعه وب')};
  const visible=useMemo(()=>projects.filter(p=>(category==='all'||p.category===category)&&`${p.title[locale]} ${p.description[locale]} ${p.technologies.join(' ')}`.toLowerCase().includes(query.toLowerCase())),[category,locale,query]);
  return <section id="projects" className="section-space bg-white dark:bg-slate-950"><div className="container-shell"><SectionHeading label={copy.projects.label} title={copy.projects.title} subtitle={copy.projects.subtitle}/><div className="mb-8 flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div className="flex flex-wrap gap-2">{categories.map(item=><button key={item} type="button" onClick={()=>setCategory(item)} className={`filter-button ${category===item?'active':''}`}>{labels[item]}</button>)}</div><label className="relative block w-full lg:max-w-sm"><Search className="pointer-events-none absolute start-4 top-1/2 -translate-y-1/2 text-slate-400" size={18}/><span className="sr-only">{copy.projects.search}</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={copy.projects.search} className="form-input ps-11"/></label></div>{visible.length===0?<div className="rounded-3xl border border-dashed border-slate-300 p-12 text-center text-slate-500 dark:border-white/15">{copy.projects.noResults}</div>:<div className="grid gap-6 lg:grid-cols-2">{visible.map((project,index)=><motion.article key={project.id} initial={{opacity:0,y:24}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.15}} transition={{delay:index*.05}} className="group overflow-hidden rounded-[1.8rem] border border-slate-200 bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-xl dark:border-white/10 dark:bg-white/5"><div className="relative overflow-hidden bg-slate-100 dark:bg-slate-900"><SmartImage src={project.image} alt={`${project.title[locale]} project preview`} loading="lazy" className="aspect-[16/9] w-full object-cover transition duration-500 group-hover:scale-[1.03]"/></div><div className="p-6"><div className="mb-3 flex items-center justify-between gap-3"><span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-black text-blue-700 dark:bg-blue-400/10 dark:text-blue-300">{project.categoryLabel[locale]}</span>{project.featured&&<span className="text-xs font-bold text-violet-600 dark:text-violet-300">{t(locale,'Featured','غوره','برگزیده')}</span>}</div><h3 className="text-2xl font-black tracking-tight text-slate-950 dark:text-white">{project.title[locale]}</h3><p className="mt-3 leading-7 text-slate-600 dark:text-slate-300">{project.description[locale]}</p><div className="mt-5 flex flex-wrap gap-2">{project.technologies.map(tech=><span key={tech} className="tech-chip">{tech}</span>)}</div><div className="mt-6 flex flex-wrap gap-3">{project.github&&<a href={project.github} target="_blank" rel="noreferrer" className="secondary-button compact"><Github size={17}/>{copy.actions.github}</a>}{project.live&&<a href={project.live} target="_blank" rel="noreferrer" className="primary-button compact"><ExternalLink size={17}/>{copy.actions.live}</a>}</div></div></motion.article>)}</div>}</div></section>;
}
