import { motion } from 'motion/react';
import { BookOpenText, Database, FlaskConical, Languages, Network, ScanText } from 'lucide-react';
import { useApp } from '../context/AppContext';
import { t } from '../lib/i18n';
import { SectionHeading } from './SectionHeading';
export function Research() {
  const {copy,locale}=useApp();
  const cards=[
    [BookOpenText,t(locale,'A Multi-Source Pashto News Dataset for Text Classification','د متن ډلبندۍ لپاره د څو سرچینو پښتو خبرونو ډیټاسېټ','دیتاست چندمنبع خبرهای پشتو برای طبقه‌بندی متن'),t(locale,'Ongoing corpus construction, annotation, preprocessing, classical ML baselines, and benchmark evaluation.','د کارپس جوړول، انوټېشن، مخکېنی پروسس، کلاسیک ML بنچمارکونه او ارزونه.','ساخت پیکره، حاشیه‌نویسی، پیش‌پردازش، مبناهای ML کلاسیک و ارزیابی بنچمارک.')],
    [Languages,t(locale,'Pashto and Dari Language Technology','د پښتو او دري ژبو ټکنالوژي','فناوری زبان پشتو و دری'),t(locale,'Low-resource text processing, multilingual interfaces, educational content, and regional-language AI.','د کم‌سرچینې متن پروسس، څوژبني انترفېسونه، تعلیمي منځپانګه او سیمه‌ییز AI.','پردازش متن کم‌منبع، رابط‌های چندزبانه، محتوای آموزشی و هوش مصنوعی زبان‌های منطقه‌ای.')],
    [Database,t(locale,'Dataset Construction and Annotation','د ډیټاسېټ جوړول او انوټېشن','ساخت دیتاست و حاشیه‌نویسی'),t(locale,'Collection strategy, schemas, cleaning, annotation guidelines, quality assurance, splits, cards, and documentation.','د راټولولو تګلاره، سکیما، پاکول، انوټېشن لارښود، کیفیت تضمین، وېش او اسناد.','راهبرد جمع‌آوری، طرح‌واره، پاک‌سازی، دستورالعمل حاشیه‌نویسی، تضمین کیفیت، تقسیم و مستندسازی.')],
    [Network,t(locale,'Custom ML and NLP Model Training','ځانګړې ML او NLP ماډل روزنه','آموزش مدل سفارشی ML و NLP'),t(locale,'Baseline selection, feature engineering, fine-tuning, evaluation, error analysis, packaging, and integration.','بنسټیز ماډلونه، فیچر انجینري، فاین‌ټیون، ارزونه، خطا تحلیل، پیکج او ادغام.','انتخاب مبنا، مهندسی ویژگی، تنظیم دقیق، ارزیابی، تحلیل خطا، بسته‌بندی و ادغام.')],
    [ScanText,t(locale,'AI for Inclusive Literacy Recovery','د ټولشموله سواد لپاره مصنوعي ځیرکتیا','هوش مصنوعی برای بازیابی سواد فراگیر'),t(locale,'Adaptive Pashto–Dari learning research using reading, writing, audio, and assessment data.','د لوست، لیک، غږ او ارزونې معلوماتو له لارې د پښتو-دري تطبیقي زده‌کړې څېړنه.','پژوهش یادگیری تطبیقی پشتو–دری با داده‌های خواندن، نوشتن، صوت و ارزیابی.')],
    [FlaskConical,t(locale,'Research Collaboration','څېړنیزه همکاري','همکاری پژوهشی'),t(locale,'Reproducible experiments, benchmark reports, datasets, student mentorship, and institutional partnerships.','تکرارېدونکي تجربې، بنچمارک راپورونه، ډیټاسېټونه، د زده‌کوونکو لارښوونه او موسساتي شراکتونه.','آزمایش‌های قابل تکرار، گزارش‌های بنچمارک، دیتاست‌ها، راهنمایی دانشجویان و همکاری‌های نهادی.')],
  ] as const;
  return <section id="research" className="section-space relative overflow-hidden bg-slate-950 text-white"><div className="absolute inset-0 bg-[radial-gradient(circle_at_20%_20%,rgba(37,99,235,.22),transparent_26%),radial-gradient(circle_at_80%_80%,rgba(124,58,237,.18),transparent_24%)]"/><div className="container-shell relative"><SectionHeading label={copy.research.label} title={copy.research.title} light/><div className="mb-8 rounded-3xl border border-blue-400/20 bg-blue-400/10 p-6"><p className="text-xs font-black uppercase tracking-[.18em] text-blue-300">{copy.research.publication}</p><h3 className="mt-3 text-2xl font-black">A Multi-Source Pashto News Dataset for Text Classification: Corpus Construction, Annotation, and Benchmark Evaluation</h3><p className="mt-3 text-slate-300">{t(locale,'Research status: ongoing. It is not presented as published unless publication is independently verified.','د څېړنې حالت: روانه ده. تر تایید پرته د خپرې شوې څېړنې په توګه نه وړاندې کېږي.','وضعیت پژوهش: در حال انجام. تا زمان تأیید مستقل، به‌عنوان اثر منتشرشده معرفی نمی‌شود.')}</p></div><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{cards.map(([Icon,title,text],index)=><motion.article key={title} initial={{opacity:0,y:24}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:index*.06}} className="rounded-3xl border border-white/10 bg-white/[.055] p-6 backdrop-blur-xl"><span className="mb-5 grid size-12 place-items-center rounded-2xl bg-blue-500/15 text-blue-300"><Icon size={24}/></span><h3 className="text-xl font-black">{title}</h3><p className="mt-3 leading-7 text-slate-300">{text}</p></motion.article>)}</div></div></section>;
}
